# Generated by Django 3.0.3 on 2020-02-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('genus', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=10, unique=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='website.Type')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='website.Type')),
            ],
        ),
    ]
